# Use a imagem base do Node.js
FROM node:18

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie os arquivos `package.json` e `package-lock.json` para instalar as dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código para o diretório de trabalho no container
COPY . .

# Gere o Prisma Client
RUN npx prisma generate

# Exponha a porta que o servidor usará
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "dev"]
